#!/bin/bash

# ${1}: config node
# ${2}: ntp mode(server/client)
# ${3}: upstream ntp server

nodes="/etc/puppet/manifests/"
ntp_class_manifests="/etc/puppet/modules/ntp/manifests/"
ntp_resource_path="/etc/puppet/modules/ntp/files/"
if [ ! -d "${ntp_resource_path}" ]; then
    mkdir -p "${ntp_resource_path}"
fi
if [ "${2}" == "server" ];then
    cat /usr/share/puppet-opestack-newton/puppet-openstack/common/ntp/ntp.conf.server | \
    sed "s/%DC_NTP_SERVER%/${3}/g" > "${ntp_resource_path}ntp.conf"
else
    cat /usr/share/puppet-opestack-newton/puppet-openstack/common/ntp/ntp.conf.client | \
    sed "s/%CLUSTER_NTP_SERVER%/${3}/g" > "${ntp_resource_path}ntp.conf"
fi

if [ ! -d "${ntp_class_manifests}" ]; then
    mkdir -p "${ntp_class_manifests}"
fi

if [ ! -f "${ntp_class_manifests}init.pp" ]; then
    cp /usr/share/puppet-opestack-newton/puppet-openstack/common/ntp/init.pp "${ntp_class_manifests}"
fi

if [ ! -d "${nodes}nodes" ];then
    mkdir "${nodes}nodes"
fi

echo "node '${1}' { include ntp }" > "${nodes}nodes/${1}.pp"
if [ $(cat "${nodes}site.pp" | egrep -v "^#" | grep "${1}" | wc -l) -eq 0 ] ; then
    echo "import \"nodes/${1}.pp\"" >> "${nodes}site.pp"
fi
puppet kick "${1}"
