#! /bin/bash

# ${1}: config node

nodes="/etc/puppet/manifests/"
rdo_modules="/etc/puppet/modules/"

if [ $(ls -l ${rdo_modules} | grep rdo | wc -l) -eq 0 ]; then
    mkdir -p "${rdo_modules}rdo"
    cp -r /usr/share/puppet-opestack-newton/puppet-openstack/common/rdo/manifests "${rdo_modules}rdo/"
fi

if [ ! -d "${nodes}nodes" ];then
    mkdir "${nodes}nodes"
fi

echo "node '${1}' { include rdo }" > "${nodes}nodes/${1}.pp"
if [ $(cat "${nodes}site.pp" | egrep -v "^#" | grep "${1}" | wc -l) -eq 0 ] ; then
    echo "import \"nodes/${1}.pp\"" >> "${nodes}site.pp"
fi
puppet kick "${1}"
