#! /bin/bash

keystone_httpd_conf="/usr/share/keystone/wsgi-keystone.conf"
keystone_host="$(cat /tmp/host)"
httpd_confs="/etc/httpd/conf.d/"
keystone_admin_passwd=$(cat /tmp/dashboard-admin-pass)

sed -i "s/^#\{0,1\}ServerName .*/ServerName ${keystone_host}/g" /etc/httpd/conf/httpd.conf
if [ $(ls -l ${httpd_confs} | grep ${keystone_httpd_conf} | wc -l) -eq 0 ];then
    ln -s ${keystone_httpd_conf} ${httpd_confs} 
fi

systemctl enable httpd
systemctl restart httpd

cat > /root/keystone_admin << EOF
export OS_USERNAME=admin
export OS_PASSWORD=${keystone_admin_passwd}
export OS_PROJECT_NAME=admin
export OS_USER_DOMAIN_NAME=Default
export OS_PROJECT_DOMAIN_NAME=Default
export OS_AUTH_URL=http://${keystone_host}:35357/v3
export OS_IDENTITY_API_VERSION=3
export OS_IMAGE_API_VERSION=2
EOF
