#! /bin/bash

root_passwd=$(cat /tmp/mysql_root_passwd)
keystone_passwd=$(cat /tmp/mysql_keystone_passwd)
mysql_host=$(cat /tmp/mysql_host_ip)

if [ $(mysql -uroot -p"${root_passwd}" -e "SHOW DATABASES" | grep keystone | wc -l) -eq 0 ]; then
    mysql -uroot -p"${root_passwd}" -e "CREATE DATABASE keystone"
fi
mysql -uroot -proot -e "GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'localhost' IDENTIFIED BY '${keystone_passwd}'"
mysql -uroot -proot -e "GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'%' IDENTIFIED BY '${keystone_passwd}'"
mysql -uroot -proot -e "GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'${mysql_host}' IDENTIFIED BY '${keystone_passwd}'"
