#! /bin/bash

mysql_root_passwd=$(cat /tmp/mysql_root_passwd)
mysql_glance_passwd=$(cat /tmp/mysql_glance_passwd)
glance_host_ip=$(cat /tmp/glance_host_ip)
glance_host=$(cat /tmp/glance_host)
glance_user_passwd=$(cat /tmp/glance_user_passwd)

if [ $(mysql -u"root" -p"${mysql_root_passwd}" -e "SHOW DATABASES"|grep glance|wc -l) -eq 0 ];then
    mysql -u"root" -p"${mysql_root_passwd}" -e "CREATE DATABASE glance"
fi

mysql -u"root" -p"${mysql_root_passwd}" -e "GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'localhost' IDENTIFIED BY '${mysql_glance_passwd}'"
mysql -u"root" -p"${mysql_root_passwd}" -e "GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'%' IDENTIFIED BY '${mysql_glance_passwd}'"
mysql -u"root" -p"${mysql_root_passwd}" -e "GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'${glance_host_ip}' IDENTIFIED BY '${mysql_glance_passwd}'"

source /root/keystone_admin
if [ $(openstack user list|awk '{print $4}'|grep -v Name|egrep -v "^$"|grep glance|wc -l) -eq 0 ];then
    openstack user create --domain default --password ${glance_user_passwd} glance
fi
openstack role add --project service --user glance admin

if [ $(openstack service list|grep glance|wc -l) -eq 0 ];then
    openstack service create --name glance --description "OpenStack Image" image
fi

if [ $(openstack endpoint list|grep public|grep glance|wc -l) -eq 0 ];then
    openstack endpoint create --region RegionOne image public   http://${glance_host}:9292
fi

if [ $(openstack endpoint list|grep internal|grep glance|wc -l) -eq 0 ];then
    openstack endpoint create --region RegionOne image internal http://${glance_host}:9292
fi

if [ $(openstack endpoint list|grep admin|grep glance|wc -l) -eq 0 ];then
    openstack endpoint create --region RegionOne image admin    http://${glance_host}:9292
fi

if [ $(rpm -qa | grep openstack-glance | wc -l) -eq 0 ];then
    yum install -y openstack-glance
fi

# CONFIG: /etc/glance/glance-api.conf
ini-config /etc/glance/glance-api.conf database connection mysql+pymysql://glance:${mysql_glance_passwd}@${glance_host_ip}/glance
ini-config /etc/glance/glance-api.conf keystone_authtoken auth_uri http://${glance_host}:5000
ini-config /etc/glance/glance-api.conf keystone_authtoken auth_url http://${glance_host}:35357
ini-config /etc/glance/glance-api.conf keystone_authtoken memcached_servers ${glance_host}:11211
ini-config /etc/glance/glance-api.conf keystone_authtoken auth_type password
ini-config /etc/glance/glance-api.conf keystone_authtoken project_domain_name Default
ini-config /etc/glance/glance-api.conf keystone_authtoken user_domain_name Default
ini-config /etc/glance/glance-api.conf keystone_authtoken project_name service
ini-config /etc/glance/glance-api.conf keystone_authtoken username glance
ini-config /etc/glance/glance-api.conf keystone_authtoken password ${glance_user_passwd}
ini-config /etc/glance/glance-api.conf paste_deploy flavor keystone
ini-config /etc/glance/glance-api.conf glance_store stores file,http
ini-config /etc/glance/glance-api.conf glance_store default_store file
ini-config /etc/glance/glance-api.conf glance_store filesystem_store_datadir /var/lib/glance/images/

# CONFIG: /etc/glance/glance-registry.conf
ini-config /etc/glance/glance-registry.conf database connection mysql+pymysql://glance:${mysql_glance_passwd}@${glance_host_ip}/glance
ini-config /etc/glance/glance-registry.conf keystone_authtoken auth_uri http://${glance_host}:5000
ini-config /etc/glance/glance-registry.conf keystone_authtoken auth_url http://${glance_host}:35357
ini-config /etc/glance/glance-registry.conf keystone_authtoken memcached_servers ${glance_host}:11211
ini-config /etc/glance/glance-registry.conf keystone_authtoken auth_type password
ini-config /etc/glance/glance-registry.conf keystone_authtoken project_domain_name Default
ini-config /etc/glance/glance-registry.conf keystone_authtoken user_domain_name Default
ini-config /etc/glance/glance-registry.conf keystone_authtoken project_name service
ini-config /etc/glance/glance-registry.conf keystone_authtoken username glance
ini-config /etc/glance/glance-registry.conf keystone_authtoken password ${glance_user_passwd}
ini-config /etc/glance/glance-registry.conf paste_deploy flavor keystone

# Init Glance DB
su -s /bin/sh -c "glance-manage db_sync" glance

# Start&Enable OpenStack-Glance-*
systemctl enable  openstack-glance-api.service openstack-glance-registry.service
systemctl restart openstack-glance-api.service openstack-glance-registry.service
